steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/subfrost-docker/fdroid:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/subfrost-docker/fdroid:latest
      - -f
      - services/fdroid/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/$PROJECT_ID/subfrost-docker/fdroid
    waitFor: [build]

  - name: gcr.io/cloud-builders/kubectl
    id: rollout
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_CONTAINER_CLUSTER=subfrost-fdroid-cluster
    args:
      - -n
      - subfrost-fdroid
      - rollout
      - restart
      - deployment/fdroid
    waitFor: [push]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/subfrost-docker/fdroid:$COMMIT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/subfrost-docker/fdroid:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM
