apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdroid
  namespace: subfrost-fdroid
  labels:
    app: fdroid
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fdroid
  template:
    metadata:
      labels:
        app: fdroid
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-request: "5m"
        gke-gcsfuse/memory-request: "128Mi"
        gke-gcsfuse/ephemeral-storage-request: "256Mi"
        gke-gcsfuse/cpu-limit: "200m"
        gke-gcsfuse/memory-limit: "512Mi"
        gke-gcsfuse/ephemeral-storage-limit: "1Gi"
    spec:
      serviceAccountName: fdroid
      containers:
        - name: fdroid
          image: us-central1-docker.pkg.dev/night-wolves-jogging/subfrost-docker/fdroid:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: fdroid-bucket
              mountPath: /fdroid
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: tls
              mountPath: /etc/nginx/tls
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 600
            periodSeconds: 30
            failureThreshold: 6
      volumes:
        - name: fdroid-bucket
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: subfrost-fdroid
              mountOptions: "implicit-dirs,file-mode=644,dir-mode=755,uid=0,gid=0"
        - name: nginx-conf
          configMap:
            name: fdroid-nginx-conf
        - name: tls
          secret:
            secretName: fdroid-tls
