apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdroid
  namespace: subfrost-fdroid
  annotations:
    iam.gke.io/gcp-service-account: fdroid-bucket@night-wolves-jogging.iam.gserviceaccount.com
